on: pull_request
name: Git Creation Demo
jobs:
  gitIssueCreation:
    name: Git Creation Demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Git Creation Demo
        uses: bryan-nice/git-issue-creation@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_OWNER: 'snyk-matt'
          GITHUB_REPOSITORY: 'ruby-goof'
          GITHUB_ISSUE_TITLE: 'Issue title'
          GITHUB_ISSUE_BODY: 'Issue body'
